### ISSUE TITLE
spirv: cannot bitcast pointer types

### ISSUE THREAD

**Issue by FROL256** [seanbaxter/shaders#11]
I understand that this is not an error of the compiler, but there is a problem for me. Probably there is ... some solution. 
So, i have a buffer  `[[using spirv: buffer, binding(3)]] uint kgen_data[];`

And this buffer in fact does store different types of data: int, float, float2, float4, float4x4 and e.t.c. 
In some places of the code i can find something like: `float4x4 matrix = *(  (float4x4*)(kgen_data+MATRIX_OFFSET);`

Well, yes, yes, i know ) 
I think that i can change particulary my code to UBO to prevent such 'great' things happening, but the problems is that:
1) in some cases it still may be needed; 
2) in clspv such code works and this mean it can be done actually in some way.

So, my question is whether you are going to implement pointer casts or it is recommended to avoid pointer casts at all costs. Thanks!

**Comment by seanbaxter** [comment]
SPIR-V for shaders (as opposed to OpenCL) doesn't allow casts on pointer types. I'd suggest uintBitsToFloat. There are overloads of that for all vector sizes.

However, I believe the bindless VK_EXT_buffer_device_address feature should allow that (if I were to implement it). Instead of using an SSBO you'd just access the device memory through a pointer.

See the vk_transform project in mgpu-shaders. This uses a pointer instead of an SSBO binding to access memory. Only a subset of pointer operations are implemented right now, but I can flesh it out to do the bitcast you show there.

**Comment by FROL256** [comment]
>> SPIR-V for shaders (as opposed to OpenCL) doesn't allow casts on pointer types
except for "__global" pointers, yep, sorry i didn't elaborate on this.

cool, thanks!
